# Generated by Django 4.2.1 on 2023-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('celular', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('dtnasc', models.TextField(max_length=255)),
            ],
        ),
    ]
